language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_61e903060b97_key -iv $encrypted_61e903060b97_iv
  -in id_rsa.enc -out /home/travis/id_rsa -d
- chmod 600 /home/travis/id_rsa
script: 
after_success:
- ssh -i /home/travis/id_rsa -tt root@118.24.95.125 < ./run.sh
addons:
  ssh_known_hosts: 118.24.95.125
